### ISSUE TITLE
FEDS - Updates to Feds Config to support context aware SERP for Blogs

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#477] opened 2020-10-26 18:14 UTC
@narcis-radu to help add a new property to Blog templates to support context aware SERP implementation for Blogs

cc @rofe

**Comment by rofe** [comment] 2020-10-27 12:58
@avanishgandhi, @narcis-radu: Isn't this a duplicate of #346

**Closed** 2020-11-02 12:58 UTC
